version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "feat"
      prefix-development: "dev"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "twilio"
        dependency-type: "production"
      - dependency-name: "*"
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
