name: auto-merge
on:
  pull_request:
    types:
      - labeled
      - opened

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: ${{ (github.event.action == 'labeled' && github.event.label.name == 'automerge') || github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
