name: auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ github.actor }}

      - name: Enable auto-merge
        if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'github-actions[bot] }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
