name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: 'npm'

      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test
      - run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Get release version
        id: get_release_version
        run: |
          twilio_version=$(npm info twilio version | xargs echo)
          echo "twilio_version=$twilio_version" >> $GITHUB_OUTPUT

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          release-as: ${{ steps.get_release_version.outputs.twilio_version }}
          token: ${{ secrets.SOMLENG_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node
        uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version-file: ".tool-versions"
          cache: 'npm'

      - name: Setup node packages
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm ci
          npm run build
          # npm publish
