name: Pre-release
on: push

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: 'npm'

      - name: Setup node packages
        run: |
          npm ci
          npm run build

      - name: Get release version
        id: get_release_version
        run: |
          twilio_version=$(npm info twilio version | xargs echo)
          somleng_version=$(npm pkg get version | xargs echo)
          echo "twilio_version=$twilio_version" >> $GITHUB_OUTPUT
          echo "somleng_version=$somleng_version" >> $GITHUB_OUTPUT

      - uses: google-github-actions/release-please-action@v3
        id: pre-release
        if: ${{ steps.get_release_version.outputs.twilio_version != steps.get_release_version.outputs.somleng_version }}
        with:
          release-type: node
          release-as: ${{ steps.get_release_version.outputs.twilio_version }}
          labels: 'release'

      - name: Auto merge PR
        if: ${{ steps.pre-release.outputs.pr }}
        run: |
          echo ${{ steps.pre-release.outputs.pr }}
          gh pr merge --auto --merge "${{ fromJSON(steps.pre-release.outputs.pr).number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.SOMLENG_PERSONAL_ACCESS_TOKEN }}
