name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: 'npm'

      - name: Setup node packages
        run: |
          npm ci
          npm run build

      - name: Get release version
        id: get_release_version
        run: |
          twilio_version=$(npm info twilio version | xargs echo)
          somleng_version=$(npm pkg get version | xargs echo)
          echo "twilio_version=$twilio_version" >> $GITHUB_OUTPUT
          echo "somleng_version=$somleng_version" >> $GITHUB_OUTPUT

      - uses: google-github-actions/release-please-action@v3
        id: pre-release
        if: ${{ steps.get_release_version.outputs.twilio_version != steps.get_release_version.outputs.somleng_version }}
        with:
          release-type: node
          release-as: ${{ steps.get_release_version.outputs.twilio_version }}

      - name: Auto merge PR
        if: ${{ steps.pre-release.outputs.pr }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ fromJSON(steps.pre-release.outputs.pr).number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: pre-release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
